<?php
/**
 *Author Marcelo Barrera
 * Implementa hook_menu().
 */

function mail_menu() {

  $items['mail'] = array(
    'title' => 'Mail',
    'page callback' => 'mail_prueba',
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Callback que implementa la páina: sw/rest
 */
function mail_prueba() {

    $module = 'module_name';
    $key = 'key';
    $language = language_default();
    $params = array();
    $from = NULL;
    $send = FALSE;
    $message = drupal_mail($module, $key,"marcelobarrera556@gmail.com" , $language, $params, "mbarrera@kakhikhelo.net", $send);
    $message['subject'] = "fracaso3";
    $message['body'] = array();
    $message['body'][] = "some";
    $message['body'][] =htmlentities('<h1>some2</h1>');
    $message['headers']['Content-Type'] = 'text/html; charset=UTF-8;';

    // Retrieve the responsible implementation for this message.
    $system = drupal_mail_system($module, $key);


    // Format the message body.
    $message = $system->format($message);


    // Send e-mail.
   // $message['result'] = $system->mail($message);
	
	if ($system->mail($message)){return "enviado";}
	else {return "no enviado";}

}


?>
