<?php
/**
 *Author Marcelo Barrera
 * Implementa hook_menu().
 */

function pruebas_menu() {

  $items['pruebas/rest'] = array(
    'title' => 'Pruebas',
    'page callback' => 'pruebas_rest',
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Callback que implementa la páina: sw/rest
 */
function pruebas_rest() {
            $node = node_load(1);
            //Nombre de la imagen
	print_r($node);

	echo "<br><br>-----Nombre de un archivo------<br>";
	print_r($node->field_image[und][0][filename]);

	echo "<br><br>-- Obtencion de la url---------<br><br>";
	print_r(file_create_url($node->field_image[und][0][uri]));

	echo "<br><br>----Clasificacion obtenida por el nodo-----<br>";
	$terms=field_view_field('node',$node,'field_tags');
	$term_name = $terms['#items'][0]['taxonomy_term']->name;
	print_r($term_name);

	echo "<br><br>----Obteniendo todos las clasificaciones-------<br>";
	$terms = taxonomy_get_tree(1);
	foreach($terms as $term){
		print_r($term->name);
		echo "<br>";
	}

	echo "<br><br>----Obteniendo todos las clasificaciones v2-------<br>";

	$categorias=array();
	$terms = taxonomy_get_tree(1);
	foreach($terms as $term){
		$valores=split(" ",$term->name);
		foreach($valores as $valor){
			//echo $valor."<br>";	
			array_push($categorias,$valor); //si sirve
		}
	}
	//print_r($categorias);
	//echo "<br>";
	$resultado = array_unique($categorias);
	$categorias=array();
	foreach($resultado as $key=>$valor){
		array_push($categorias,array("titulo"=>$valor)); //si sirve
		#echo $valor."<br>";
	}
	//print_r($categorias);
	//echo "<br>";
	$categorias=array("categorias" => $categorias);
	echo json_encode($categorias);
}

?>
